default: &default
  adapter: jdbcpostgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coding_platform_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: coding_platform_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
